/*
Authors: Jared Daniel, Harris Siddiqui, Griffin Apida, Yifan Liu
 */

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Lab10Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:/Users/Jared/OneDrive - The Pennsylvania State University/Documents/Penn State/6th Semester/SWENG 431/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void test() throws InterruptedException
    {
        driver.get("https://docs.oracle.com/javase/9/docs/api/overview-summary.html");
        driver.manage().window().setSize(new Dimension(1166, 797));
        driver.findElement(By.linkText("Java SE")).click();
        driver.findElement(By.id("search")).click();
        driver.findElement(By.id("search")).sendKeys("java.lang.String");
        Thread.sleep(2000);
        driver.findElement(By.id("search")).sendKeys(Keys.ENTER);
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(2000));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")));
        }
        Thread.sleep(2000);
        driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
        Thread.sleep(2000);
        driver.findElement(By.id("search")).click();
        driver.findElement(By.id("search")).sendKeys("JFrame");
        Thread.sleep(2000);
        driver.findElement(By.id("search")).sendKeys(Keys.ENTER);
        {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(2000));
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")));
        }
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.cssSelector(".altColor:nth-child(4) > .colConstructorName .memberNameLink > a")).click();
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
//        driver.findElement(By.id("search")).click();
//        driver.findElement(By.id("search")).sendKeys("String");
//        driver.findElement(By.id("search")).sendKeys(Keys.ENTER);
//        try {
//            Thread.sleep(3000);
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }
//        {
//            WebDriverWait wait = new WebDriverWait(driver, Duration.ofMillis(5000));
//            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")));
//        }
//        driver.findElement(By.cssSelector(".rowColor:nth-child(3) > .colConstructorName a")).click();
    }
}
